feat: add sql autocomplete
wix/quix pull request #361
Opened 2021-09-02 15:58 UTC by tamirhr

2021-09-02 16:04 UTC, tamirhr commented
we need to check the problem that occurs during the tests.
@odedkwix

2021-09-06 08:19 UTC, antonpodolsky requested changes
Looks good overall. For now just some general comments.
Later we'll deep dive a little more into implementation.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/adapter/types.ts
> +import { QueryContext } from "../sql-context-evaluator/types";
use single quotes for strings.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/index.ts
> +export {
please export each property in this object individually.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/context-evaluator.ts
> +export default evaluateContext;
please refrain from using default exports.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/position-evaluator.ts
> +export default evaluateContextFromPosition;
please refrain from using default exports.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/presto-context-listener.ts
> +  private _identifier: string;
No need for prefixing private class members with '_'.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/tree-analyzer.ts
> +  return [currentTableInfo];
there's a bit of disconnect between what the function returns and how it's named.
I suppose it can be called something like `getRelationInfo`.

2021-09-06 08:19 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/sql-context-evaluator/tree-analyzer.ts
> +  return { tables, columns, selectAll };
same here

2021-09-09 08:26 UTC, odedkwix commented on quix-frontend/client/src/lib/sql-autocomplete/adapter/sql-autocomplete-adapter.ts
> +    return [...completersMemory].map((completer) =>
the destruction is here because completersMemory is a set created to avoid duplicates...is there another way to use map on a set?

2021-09-09 09:34 UTC, antonpodolsky commented on quix-frontend/client/src/lib/sql-autocomplete/adapter/sql-autocomplete-adapter.ts
> +    return [...completersMemory].map((completer) =>
my bad, I missed the fact that it's a set. that's the correct way to do it.

2021-09-12 08:44 UTC, merged